- job-template:
    name: 'sandbox-noop-check-communication'
    node: '{node}'

    builders:
      - shell: |
          #!/bin/bash -xe
          echo "Hello world, this is MyVendor's Testing System"

    publishers:
      - console-log  # In macros.yaml from os-ext-testing


- job-template:
    name: 'sandbox-dsvm-tempest-full'
    node: '{node}'

    wrappers:
      - timeout:
          timeout: 185  # Timeout in *minutes*
          fail: true  # A job run that exceeds the timeout will cause a failure
      - timestamps

    builders:
      - devstack-checkout  # In macros.yaml from os-ext-testing
      - shell: |
          #!/bin/bash -xe
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TIMEOUT=180
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_VOLUME_API=1
          export RE_EXEC=true
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
      - link-logs  # In macros.yaml from os-ext-testing

    publishers:
      - devstack-logs  # In macros.yaml from os-ext-testing
      - console-log  # In macros.yaml from os-ext-testing
